In [7]:
import numpy as np
import pandas as pd
import altair as alt
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import geopandas as gpd
import json
from pyproj import Proj
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

In [18]:
# create GeoPandas Dataframe of the neighbourhood boundaries
# load the geojson file
geo_json_file_loc= 'Data/local-area-boundary.geojson'

def open_geojson():
    with open(geo_json_file_loc) as json_data:
        d = json.load(json_data)
    return d

def get_gpd_df():
    vancouver_json = open_geojson()
    gdf = gpd.GeoDataFrame.from_features((vancouver_json))
    return gdf

gdf = get_gpd_df()

In [23]:
# load crime data
df = pd.read_csv("Data/crimedata_csv_all_years.csv")

# Data Wrangling
df = df[["NEIGHBOURHOOD", "TYPE"]]
df['NEIGHBOURHOOD'] = df['NEIGHBOURHOOD'].str.replace("Musqueam", "Marpole",regex = True)
df['NEIGHBOURHOOD'] = df['NEIGHBOURHOOD'].str.replace("Stanley Park", "West End",regex = True)

In [26]:
df['TYPE'].unique()

array(['Break and Enter Commercial', 'Break and Enter Residential/Other',
       'Homicide', 'Mischief', 'Offence Against a Person', 'Other Theft',
       'Theft from Vehicle', 'Theft of Bicycle', 'Theft of Vehicle',
       'Vehicle Collision or Pedestrian Struck (with Fatality)',
       'Vehicle Collision or Pedestrian Struck (with Injury)'],
      dtype=object)

In [20]:
gdf = gdf.merge(df, left_on='name', right_on='NEIGHBOURHOOD', how='inner')

In [21]:
choro_json = json.loads(gdf.to_json())
choro_data = alt.Data(value=choro_json['features'])

KeyboardInterrupt:

In [ ]:
geo_json_file_loc= 'Data/local-area-boundary.geojson'


def open_geojson():
    with open(geo_json_file_loc) as json_data:
        d = json.load(json_data)
    return d

def get_gpd_df():
    vancouver_json = open_geojson()
    gdf = gpd.GeoDataFrame.from_features((vancouver_json))
    return gdf

gdf = get_gpd_df()

df = pd.read_csv("Data/crimedata_csv_all_years.csv")

# Data Wrangling
df = df[["NEIGHBOURHOOD", "TYPE"]]
df['NEIGHBOURHOOD'] = df['NEIGHBOURHOOD'].str.replace("Musqueam", "Marpole",regex = True)
df['NEIGHBOURHOOD'] = df['NEIGHBOURHOOD'].str.replace("Stanley Park", "West End",regex = True)
df.groupby(by='NEIGHBOURHOOD').count()

In [ ]:
gdf = gdf.merge(df, left_on='name', right_on='NEIGHBOURHOOD', how='inner')
gdf

In [ ]:
# mapping function based on all of the above

    # Add Base Layer
base = alt.Chart(gdf).mark_geoshape(
        stroke='black',
        strokeWidth=1
    ).encode(
    ).properties(
        width=300,
        height=300
    )
    # Add Choropleth Layer
choro = alt.Chart(df).mark_geoshape(
            fill='lightgray',
        stroke='black'
    ).encode(
             tooltip=[alt.Tooltip('properties.Name:O', title = 'Neighbourhood'),
                                   alt.Tooltip('properties.YEAR:Q', title = 'Crime Count')])

base + choro

In [81]:
len(df['NEIGHBOURHOOD'].unique())

25

In [96]:
data=(df['NEIGHBOURHOOD'].unique())

In [104]:
data[1]

'Fairview'

In [113]:
gdf

,geometry,mapid,name,geo_point_2d
0,"POLYGON ((-123.15260 49.25723, -123.16488 49.2...",AR,Arbutus-Ridge,"[49.2468049108, -123.161669238]"
1,"POLYGON ((-123.11227 49.29016, -123.10424 49.2...",CBD,Downtown,"[49.2807470711, -123.116567008]"
2,"POLYGON ((-123.14599 49.25712, -123.14540 49.2...",FAIR,Fairview,"[49.2645404871, -123.131048865]"
3,"POLYGON ((-123.07702 49.29025, -123.06778 49.2...",GW,Grandview-Woodland,"[49.2764396102, -123.066728221]"
4,"POLYGON ((-123.05649 49.29349, -123.05190 49.2...",HS,Hastings-Sunrise,"[49.277934053, -123.040269923]"
5,"POLYGON ((-123.10696 49.20416, -123.11153 49.2...",MARP,Marpole,"[49.2102074666, -123.12838166]"
6,"POLYGON ((-123.10562 49.23312, -123.11617 49.2...",RP,Riley Park,"[49.2447664796, -123.103146806]"
7,"POLYGON ((-123.15527 49.23452, -123.15508 49.2...",SHAU,Shaughnessy,"[49.2456809771, -123.139760167]"
8,"POLYGON ((-123.09929 49.28927, -123.09390 49.2...",STR,Strathcona,"[49.2782195786, -123.088235281]"
9,"POLYGON ((-123.13768 49.27532, -123.14126 49.2...",WE,West End,"[49.2850111894, -123.135437653]"
10,"POLYGON ((-123.17017 49.24789, -123.17025 49.2...",DS,Dunbar-Southlands,"[49.2379619063, -123.189546803]"
11,"POLYGON ((-123.17908 49.21556, -123.17564 49.2...",KERR,Kerrisdale,"[49.2236554855, -123.159576182]"
12,"POLYGON ((-123.02356 49.20015, -123.03998 49.2...",KIL,Killarney,"[49.2170216717, -123.037647029]"
13,"POLYGON ((-123.13768 49.27532, -123.14375 49.2...",KITS,Kitsilano,"[49.2675398494, -123.16329474]"
14,"POLYGON ((-123.11599 49.23794, -123.11617 49.2...",SC,South Cambie,"[49.2455564633, -123.121800916]"
15,"POLYGON ((-123.05683 49.20420, -123.05846 49.2...",VF,Victoria-Fraserview,"[49.220011941, -123.064134718]"
16,"POLYGON ((-123.05659 49.26198, -123.05663 49.2...",KC,Kensington-Cedar Cottage,"[49.2466864472, -123.072884592]"
17,"POLYGON ((-123.10067 49.26913, -123.09692 49.2...",MP,Mount Pleasant,"[49.2630652507, -123.09851312]"
18,"POLYGON ((-123.10562 49.23312, -123.10616 49.2...",OAK,Oakridge,"[49.2264031973, -123.123024604]"
19,"POLYGON ((-123.02356 49.23479, -123.02357 49.2...",RC,Renfrew-Collingwood,"[49.2473427346, -123.040166465]"
20,"POLYGON ((-123.10696 49.20416, -123.10616 49.2...",SUN,Sunset,"[49.2187561515, -123.092038001]"
21,"POLYGON ((-123.22445 49.27892, -123.20515 49.2...",WPG,West Point Grey,"[49.2684012111, -123.203467483]"

In [116]:
df.query('NEIGHBOURHOOD=="Musqueam"')

,NEIGHBOURHOOD,YEAR,MONTH,DAY,HOUR,MINUTE,TYPE
22882,Musqueam,2003,2,9,5,30,Break and Enter Commercial
22883,Musqueam,2003,3,31,1,5,Break and Enter Commercial
22884,Musqueam,2003,3,31,3,36,Break and Enter Commercial
22885,Musqueam,2005,6,27,4,10,Break and Enter Commercial
22886,Musqueam,2005,8,7,23,30,Break and Enter Commercial
...,...,...,...,...,...,...,...
619819,Musqueam,2006,8,27,0,6,Vehicle Collision or Pedestrian Struck (with I...
619820,Musqueam,2015,5,24,8,36,Vehicle Collision or Pedestrian Struck (with I...
619821,Musqueam,2013,8,8,20,18,Vehicle Collision or Pedestrian Struck (with I...
619822,Musqueam,2015,8,16,4,5,Vehicle Collision or Pedestrian Struck (with I...
619838,Musqueam,2019,5,8,19,11,Vehicle Collision or Pedestrian Struck (with I...

In [129]:
data=df['NEIGHBOURHOOD'].unique()

In [132]:
pd.DataFrame({'Column1': data[0:23]})

                      Column1
0                    Oakridge
1                    Fairview
2                    West End
3   Central Business District
4            Hastings-Sunrise
5                  Strathcona
6          Grandview-Woodland
7                   Kitsilano
8    Kensington-Cedar Cottage
9                      Sunset
10             Mount Pleasant
11                Shaughnessy
12                    Marpole
13            West Point Grey
14        Victoria-Fraserview
15                 Kerrisdale
16                 Riley Park
17              Arbutus Ridge
18        Renfrew-Collingwood
19                  Killarney
20          Dunbar-Southlands
21               South Cambie
22                        NaN